# Generated by Django 5.1.4 on 2025-01-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enduser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password1', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Shopee',
        ),
    ]
