# Generated by Django 5.1.4 on 2025-01-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enduser', '0003_cart_useraccount_delete_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
