# Generated by Django 5.1.4 on 2025-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_userdata_delete_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
